export * from './today/today.component';
export * from './class-attendance/class-attendance.component';
export * from './class-analytics/class-analytics.component';
export * from './class-activities/class-activities.component';
export * from './teacher-timetable/teacher-timetable.component';
export * from './teacher-personal/teacher-personal.component';
export * from './class-assignments/class-assignments.component';
export * from './exam-centre/exam-centre.component';
export * from './teacher-dashboard-home/teacher-dashboard-home.component';
